#!/bin/bash
#
#This script will perform below tasks based on the arguments:
#1) Sync data from xnat based on input.
#2) Create data structure and run dcm2bids.
#3) Convert/split multivolume topup files.
#4) Apply intendedFor and taskName.
#5) Run bids-validator on the data.
#
#
###### BEGIN ########
#Usage message to display
usage()
{
  echo -en "\nSYNTAX ERROR\n"
  echo -e "usage: $0 [ -d directory -p project_id -a arguments ]\n"
  echo -e "Where directory is before the projects\n"
  echo -en "[arguments] can be:\n
Individual:
            [sync] - Sync xnat data.
         [convert] - Convert and run dcm2bids on data. After sync is completed.
           [split] - Split multivolume data. After sync and convert is completed.
          [intend] - Apply intendedFor and taskName
           [valid] - Run bids validator.

Combined:
   [synctoconvert] - sync + convert
     [synctosplit] - sync + convert + split
    [synctointend] - sync + convert + split + intend
     [synctovalid] - sync + convert + split + intend + valid
  [converttosplit] - convert + split
 [converttointend] - convert + split + intend
  [converttovalid] - convert + split + intend + valid
   [splittointend] - split + intend
    [splittovalid] - split + intend + valid
   [intendtovalid] - intend + valid\n\n"
}
#
if [ "$1" == "" ]; then
  usage
  exit 1
fi

if [[ $# -eq 1 ]]; then
  usage
  exit
fi

if [[ $# -lt 3 ]]; then
  usage
  exit 1
fi

while [ "$1" != "" ]; do
    case $1 in
        -d )           shift
                       dept=$1
                       ;;
        -p )           shift
                       projid=$1
                       ;;
        -a)            shift
                       arg=$1
                       ;;
        * )            usage
                       exit 1
    esac
    shift
done
#
#List of acceptable arguments
listofarg="
sync
convert
split
intend
valid
synctoconvert
synctosplit
synctointend
synctovalid
converttosplit
converttointend
converttovalid
splittointend
splittovalid
intendtovalid
"

totalarg=`echo $listofarg | sed 's/ /|/'g`

if ! [[ "$arg" =~ ^($totalarg)$ ]]; then
        echo -en "\nERROR: INCORRECT ARGUMENT\n"
        usage
        exit 1
fi
#
### Assuming below directory structure ####
### Example:
### dept=directory
### List path: /baseDIR/dept/projectID/scripts/projectID_working.lst
### Raw data path: /baseDIR/dept/projectID/rawdata/
### Subject path: /baseDIR/dept/projectID/rawdata/sub-subjectID/
### d2b-template_projectID.json path: /baseDIR/dept/projectID/d2b-template_projectID.json
### dataset_description.json path: /fileloc/dataset_description.json
### participants.tsv path: /fileloc/participants.tsv
###
### To run from a different host or different path, 3 variables need to be changed
### "basedir", "dept" and "fileloc"
### In this script, basedir=/MRI_DATA
###                 dept=nyspi
###            and, fileloc=/usr/local/pipelines
#
#
user=`id -un`
homedir=`echo ~`
image="nyspishared/bidsprep:latest"
basedir="/MRI_DATA"
#
#Ask for xnat username and password only if running sync 
if [[ "$arg" = *sync* ]]; then
# Check if netrc file is not present
        if ! [[ $(ls -d ${basedir}/.xnatrc/.netrc_${user} 2>/dev/null) ]] ; then
                ## If netrc file is not present, Ask for xnat username and password
                read -p "Enter XNAT username: " xnatname
                read -s -p "Password: " xnatpass
                (cat <<<"machine xnat.nyspi.org login ${xnatname} password ${xnatpass}") > ${basedir}/.xnatrc/.netrc_${user} && chown ${user} ${basedir}/.xnatrc/.netrc_${user} && chmod 600 ${basedir}/.xnatrc/.netrc_${user}
                echo
        fi
fi
#
prodir=${basedir}/${dept}
listpath=${prodir}/${projid}/scripts
tmpdir=${prodir}/${projid}/tmp
xnatdir="/XNATdata"
#
#default description and tsv file location for convertdcm:
fileloc="/usr/local/pipelines"
#
#If project list file is not present, then exit
if [ ! -f ${listpath}/${projid}_working.lst ]; then
  echo -en "\nERROR:\n${projid}_working.lst is not present under ${listpath}/.\nCannot proceed without this file.\n\n"
  exit
fi
#
#If json template of the project is not present, then exit
if [ ! -f ${prodir}/${projid}/d2b-template_${projid}.json ]; then
  echo -en "\nERROR:\nd2b-template_${projid}.json file is not present under ${prodir}/${projid}/.\nCannot proceed without this file.\n\n"
  exit
fi
#If the subjects are more than 10, then exit
#if [ $(grep -c . ${listpath}/${projid}_working.lst) -gt 10 ]; then
#  echo -en "\nERROR:\nOnly 10 subjects allowed at once.\n\n"
#  exit
#fi
#
#
#Optional - Pending - to check for below files if they exist or not, and exit if not:
# pre-bidsprep-perms.sh, post-bidsprep-perms.sh, dataset_description.json, participants.tsv,
# d2b-template_${projid}.json, /bidsq.sh
#
#
#Copy below scripts:
# pre-bidsprep-perms.sh, post-bidsprep-perms.sh, dataset_description.json
# participants.tsv, d2b-template_${projid}.json

cp ${fileloc}/pre-bidsprep-perms.sh ${prodir}/.cp_pre-bidsprep-perms.sh
cp ${fileloc}/post-bidsprep-perms.sh ${prodir}/.cp_post-bidsprep-perms.sh
cp ${fileloc}/dataset_description.json ${prodir}/cp_dataset_description.json
cp ${fileloc}/participants.tsv ${prodir}/cp_participants.tsv
cp ${prodir}/${projid}/d2b-template_${projid}.json ${prodir}/cp_d2b-template_${projid}.json
#
#
#Make a temp directory
mkdir -p ${tmpdir}
# && chmod 770 ${tmpdir}
#Copy monitoring script to temp directory
cp ${fileloc}/bidsqmonitor.sh ${tmpdir}/bidsqmonitor_${projid}.sh
#Delete any previous cronjob for this specific monitoring
crontab -l | sed "/bidsqmonitor_${projid}/d" | crontab -
#Empty/Create a file inside temp directory that has a list service names used for monitoring
cat /dev/null > ${tmpdir}/${projid}_working.service.lst
#Backup the original working list file
if ! [[ $(ls -d ${listpath}/${projid}_working.lst.orig 2>/dev/null) ]] ; then cp ${listpath}/${projid}_working.lst ${listpath}/${projid}_working.lst.orig; fi
#Create a temp file of the original working list inside temp directory
if ! [[ $(ls -d ${tmpdir}/${projid}_working.lst.tmp 2>/dev/null) ]] ; then cp ${listpath}/${projid}_working.lst ${tmpdir}/${projid}_working.lst.tmp; fi
#If tmp file is empty, then delete the whole temp directory and exit
if [ $(cat ${tmpdir}/${projid}_working.lst.tmp | wc -l) == 0 ]; then
        mv ${listpath}/${projid}_working.lst.orig ${listpath}/${projid}_working.lst \
        && rm -rf ${tmpdir} 2>/dev/null
        exit
fi
#
if [[ "$arg" = *sync* ]]; then
        netrcmount="--mount type=bind,source=${basedir}/.xnatrc/.netrc_${user},destination=/.nrc/.netrc"
else
        netrcmount=""
fi

#Get the gid of the project group
progroup=$(cat /etc/group | grep ${projid} | cut -d ":" -f3)


#Set job limit to 5
#Copy first 5 lines of the temp working list file to the original working list file
awk 'NR >= 1 && NR <= 5' ${tmpdir}/${projid}_working.lst.tmp > ${listpath}/${projid}_working.lst
sleep 1
#Delete the first 5 lines of the temp working list file
sed -i '1,5d' ${tmpdir}/${projid}_working.lst.tmp
#
#Read the original working list file that has 5 lines and launch the jobs
#
sleep 2
grep . ${listpath}/${projid}_working.lst | while read -r line
do
subjid=$(echo $line | awk '{print $1}')
datapath="/data/${projid}/rawdata/sub-${subjid}"
exam=$(echo $line | awk '{print $3}')
accession=$(echo $line | awk '{print $4}')
#log=${prodir}/${projid}/derivatives/sub-bidsprep.log
log=${HOME}/sub-bidsprep.log
name=${dept}_${projid}_${subjid}_${exam}_${user}
echo "Starting service for ${name}" >> ${log}
nohup /usr/bin/docker service create --replicas 1 --reserve-cpu 8 --reserve-memory 16g --mode replicated --restart-condition none --name=${name} --mount type=bind,source=/MRI_DATA/xnatbidsprep/letsprocess,destination=/bin/letsprocess --mount type=bind,source=/MRI_DATA/xnatbidsprep/xnat_sync.sh,destination=/bin/xnat_sync.sh --mount type=bind,source=${xnatdir}/archive/${projid}/arc001/${exam}/SCANS,destination=/xnatscan,readonly=true --mount type=bind,source=${prodir},destination=/data --mount type=bind,source=${prodir}/.cp_pre-bidsprep-perms.sh,destination=/bin/pre-perms.sh --mount type=bind,source=${prodir}/.cp_post-bidsprep-perms.sh,destination=/bin/post-perms.sh ${netrcmount} ${image} /bin/bash -c "/bin/pre-perms.sh ${projid}; letsprocess ${datapath} ${subjid} ${projid} ${exam} ${accession} ${arg} ${progroup}; /bin/post-perms.sh ${projid}" >> ${log} 2>&1 &
echo ${name} >> ${tmpdir}/${projid}_working.service.lst
done
echo -en "Jobs submitted for project \"${projid}\" with argument \"${arg}\".\nPlease run ${fileloc}/sub-bidsmgmt to manage the jobs.\n"
#
#Monitoring the queue:
#
#Create a cronjob that runs the monitoring script every 5 mins
sleep 5
(crontab -l && echo "*/5 * * * * ${tmpdir}/bidsqmonitor_${projid}.sh ${dept} ${projid} ${arg}") | crontab -
##### END #####
